
[build]
  command = "npm run build"
  publish = "out"
  
[build.environment]
  NODE_VERSION = "20.0.0"
  NPM_VERSION = "10.2.3"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
