[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "9.6.7"
  GO_VERSION = "1.20"  # Explicitly set a stable Go version

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200